### ISSUE TITLE
Ask for help

### ISSUE THREAD

**Issue by SkyShiS** [mblo/sfctss#2]
Hello, author! I have read your paper, "Letting off STEAM:....". But I also get confused about the process of schedulers (GreedyShortestDeadlineFirstScheduler, LoadUnawareRoundRobinScheduler and MppScheduler)in this project. Do you have some introduction about these schedulers or the flow charts about how they work or pseudocodes? Thanks a lot!!!

**Comment by SkyShiS** [comment]
hello, author! I get another question that what the "oracle" means in this sentence, "if oracle, we check all SFF, if non oracle, we check only my own sff" ?

**Comment by mblo** [comment]
Hi @SkyShiS,

Here are the answers to your questions:

- **What is oracle?** If a scheduler is configured with `oracle=True`, the scheduler acts like having access to all servers of all sites. Otherwise, if a scheduler runs with `oracle=False`, it will consider only site-local SFIs for taking scheduling decisions (i.e., all SFIs the SFF is in charge of). For example, when you run `MppScheduler` with `oracle=True`, it behaves like IA-MPP. If you run it with `oracle=False`, it behaves like STEAM.
- **Do you have flow charts or pseudocode of the schedulers?** We refer to the paper (Section III, IV, and V.A) for a high level description how the schedulers work -- we don't have any flow charts. However, we highly recommend starting to read the code from the flow of the packets, i.e., start at `SFF.apply_logic_packet_from_ingress ` (https://github.com/mblo/sfctss/blob/e255af462d5c1658a1065fa4af082fde71290b55/sfctss/model/sff.py#L292)  and the two methods above and below of this method.

Hope that helps!

**Comment by SkyShiS** [comment]
Thanks for answering! That's help!!!
